Update HelpWindow
AY2223S1-CS2103T-W11-1/tp pull request #41
Opened 2022-10-11 12:31 UTC by Prearo

Closes #26 

HelpWindow displaying only a link to the user guide felt unfriendly and not very useful.

The link is updated, and the window now shows basic command usage. This makes it easier for the users to get help.

2022-10-11 20:41 UTC, charleslimjh requested changes
When cloning your repository and testing, a bug occurs due to `EateryListPanel.fxml` having this ListView referring to the wrong id. 

![image](https://user-images.githubusercontent.com/88593616/195193355-19943542-9fa0-4d5f-87d5-a7c1bf2288d6.png)

It should refer to `eateryListView` instead in Line 6, as shown here. Not sure if this has been tested on your device and is just an untracked file in your local copy of the project.

![image](https://user-images.githubusercontent.com/88593616/195193274-b62db8ad-6c57-4338-aced-f18bf9042911.png)

Otherwise, new help menu looks good. 

Just help double check back on the file `src/resources/view/EateryListPanel.fxml` before we merge this PR.

2022-10-14 01:22 UTC, garfield-oo7 reviewed
lgtm! The help window works as intended and no bugs to report off.

2022-10-14 01:58 UTC, garfield-oo7 approved these changes
lgtm

2022-10-14 03:46 UTC, charleslimjh approved these changes

2022-10-14 03:46 UTC, merged